package com.raishin.lifehack.domain;

public class Lifehack {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lifehack.id
     *
     * @mbg.generated Wed Mar 03 00:20:05 JST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lifehack.title
     *
     * @mbg.generated Wed Mar 03 00:20:05 JST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lifehack.category
     *
     * @mbg.generated Wed Mar 03 00:20:05 JST 2021
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lifehack.description
     *
     * @mbg.generated Wed Mar 03 00:20:05 JST 2021
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lifehack.id
     *
     * @return the value of lifehack.id
     *
     * @mbg.generated Wed Mar 03 00:20:05 JST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lifehack.id
     *
     * @param id the value for lifehack.id
     *
     * @mbg.generated Wed Mar 03 00:20:05 JST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lifehack.title
     *
     * @return the value of lifehack.title
     *
     * @mbg.generated Wed Mar 03 00:20:05 JST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lifehack.title
     *
     * @param title the value for lifehack.title
     *
     * @mbg.generated Wed Mar 03 00:20:05 JST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lifehack.category
     *
     * @return the value of lifehack.category
     *
     * @mbg.generated Wed Mar 03 00:20:05 JST 2021
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lifehack.category
     *
     * @param category the value for lifehack.category
     *
     * @mbg.generated Wed Mar 03 00:20:05 JST 2021
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lifehack.description
     *
     * @return the value of lifehack.description
     *
     * @mbg.generated Wed Mar 03 00:20:05 JST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lifehack.description
     *
     * @param description the value for lifehack.description
     *
     * @mbg.generated Wed Mar 03 00:20:05 JST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}