package com.raishin.lifehack.mapper;

import com.raishin.lifehack.domain.Lifehack;
import com.raishin.lifehack.domain.LifehackExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface LifehackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lifehack
     *
     * @mbg.generated Wed Mar 03 00:20:05 JST 2021
     */
    @SelectProvider(type=LifehackSqlProvider.class, method="countByExample")
    long countByExample(LifehackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lifehack
     *
     * @mbg.generated Wed Mar 03 00:20:05 JST 2021
     */
    @DeleteProvider(type=LifehackSqlProvider.class, method="deleteByExample")
    int deleteByExample(LifehackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lifehack
     *
     * @mbg.generated Wed Mar 03 00:20:05 JST 2021
     */
    @Delete({
        "delete from lifehack",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lifehack
     *
     * @mbg.generated Wed Mar 03 00:20:05 JST 2021
     */
    @Insert({
        "insert into lifehack (id, title, ",
        "category, description)",
        "values (#{id,jdbcType=INTEGER}, #{title,jdbcType=VARCHAR}, ",
        "#{category,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR})"
    })
    int insert(Lifehack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lifehack
     *
     * @mbg.generated Wed Mar 03 00:20:05 JST 2021
     */
    @InsertProvider(type=LifehackSqlProvider.class, method="insertSelective")
    int insertSelective(Lifehack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lifehack
     *
     * @mbg.generated Wed Mar 03 00:20:05 JST 2021
     */
    @SelectProvider(type=LifehackSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="category", property="category", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR)
    })
    List<Lifehack> selectByExample(LifehackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lifehack
     *
     * @mbg.generated Wed Mar 03 00:20:05 JST 2021
     */
    @Select({
        "select",
        "id, title, category, description",
        "from lifehack",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="category", property="category", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR)
    })
    Lifehack selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lifehack
     *
     * @mbg.generated Wed Mar 03 00:20:05 JST 2021
     */
    @UpdateProvider(type=LifehackSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Lifehack record, @Param("example") LifehackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lifehack
     *
     * @mbg.generated Wed Mar 03 00:20:05 JST 2021
     */
    @UpdateProvider(type=LifehackSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Lifehack record, @Param("example") LifehackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lifehack
     *
     * @mbg.generated Wed Mar 03 00:20:05 JST 2021
     */
    @UpdateProvider(type=LifehackSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Lifehack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lifehack
     *
     * @mbg.generated Wed Mar 03 00:20:05 JST 2021
     */
    @Update({
        "update lifehack",
        "set title = #{title,jdbcType=VARCHAR},",
          "category = #{category,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Lifehack record);
}